import { expect, it, vi } from 'vitest';
import { createChatActions } from '../../src/chat-actions.js';

function host() {
    const branch = { branchId: 'b', status: 'committed', segments: [{ postSnapshot: { version: 1 }, checks: [] }] }; const envelope = { stateVersion: 1, headRevision: 2, preset: { id: 'd20' }, activeSnapshot: { version: 1 }, activeRef: { messageId: 'm', swipeId: 0, branchId: 'b' } }; const message = { swipe_id: 0, extra: { dualModelEngine: { messageId: 'm' } }, swipe_info: [{ extra: { dualModelEngine: { branch } } }] }; const context = { chatId: 'c', chat: [message], chatMetadata: { dualModelEngine: envelope } };
    const store = { loadEnvelope: () => ({ ok: true, value: envelope }), commitCurrentBranchAudit: vi.fn(async () => ({ ok: true })), commitCurrentBranchMutation: vi.fn(async () => ({ ok: true })) }; const ledger = { list: () => [{ kind: 'check', checkId: 'old', branchId: 'b', request: { actor: 'p', ability: 'dexterity', skill: 'stealth', advantage: 'normal', dc: 1 } }], reroll: (old, value) => ({ ...value, checkId: 'new', supersedes: old.checkId }), commit: vi.fn(), createRecord: value => ({ ...value, checkId: 'damage' }) };
    return { store, ledger, actions: createChatActions({ adapter: { getContext: () => context }, store, ledger, queue: { enqueue: (_id, _key, task) => task(new AbortController().signal) }, orchestrator: { getActiveGeneration: () => null }, config: () => ({ enabled: true }), makeId: () => 'x', nextUint32: () => 1, preset: () => ({ readActor: () => ({ abilities: { dexterity: 10 }, proficientSkills: [], proficiencyBonus: 2 }), writeActor: () => {}, skillAbilities: { stealth: 'dexterity' }, naturalRollPolicy: 'normal' }), validateState: () => ({ ok: true, errors: [] }) }) };
}
it('rerolls only checks, preserves old record, and commits ledger after store', async () => { const h = host(); await expect(h.actions.reroll()).resolves.toMatchObject({ ok: true }); expect(h.store.commitCurrentBranchAudit).toHaveBeenCalledWith(expect.objectContaining({ record: expect.objectContaining({ supersedes: 'old' }) })); expect(h.ledger.commit).toHaveBeenCalledOnce(); });
